FROM alpine:3.20

WORKDIR /src

RUN apk add --no-cache python3

COPY . /src

RUN mkdir -p /srv \
    && tar -C /src -cf /srv/source.tar .

EXPOSE 8080

CMD ["python3", "-m", "http.server", "8080", "--directory", "/srv"]
