apiVersion: v1
kind: Service
metadata:
  name: image-factory-registry
  labels:
    app.kubernetes.io/name: image-factory-registry
    app.kubernetes.io/part-of: image-factory
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: image-factory-registry
  ports:
    - name: http
      port: 5000
      targetPort: http

