database:
  mode: external
  host: aws-1-us-east-2.pooler.supabase.com
  port: 5432
  name: postgres
  user: postgres.cqraxvwtvscccvwoggjx
  password: "REPLACE_ME"
  sslMode: require
  schema: image_factory
  maxOpenConns: 5
  maxIdleConns: 2
  connMaxLifetime: "2m"

postgres:
  enabled: false
