{{- if and .Values.ingress.enabled .Values.docs.enabled .Values.ingress.docsHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "image-factory.fullname" . }}-docs
  labels:
    {{- include "image-factory.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.ingress.docsAnnotations .Values.ingress.certManager.enabled }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer.name | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.docsAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.docsHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "image-factory.fullname" . }}-docs
                port:
                  number: {{ .Values.docs.service.port }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
